name: Auto Sync Docs

on:
  push:
    branches: [main]
    paths:
      - 'README.md'
      - 'whitepaper/**'
      - 'simulation-flow/**'
      - '.github/workflows/auto-sync-docs.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Auto Sync Logic Sections
        run: |
          python .github/scripts/sync_sections.py
