name: Contributors Bot

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  add-contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add Contributor
        uses: BobAnkh/add-contributors@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTRIBUTORS_FILE: README.md
          IMAGE_SIZE: 100
