name: Tag Logic Version

on:
  push:
    branches:
      - main
    paths:
      - 'core-logics/**'
      - 'poplashield/**'
      - 'hydraflow/**'
      - 'README.md'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          echo "LATEST_TAG=$(git describe --tags --abbrev=0 || echo 'v0.0.0')" >> $GITHUB_ENV

      - name: Bump version
        run: |
          NEW_TAG=$(python .github/scripts/bump_version.py $LATEST_TAG)
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG
